version: '3.9'

services:
  api:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
     - "5126:8080" #Host:Container
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - Groq__ApiKey=${GROQ_API_KEY}
     - ConnectionStrings__DefaultConnection=Data Source=/app/app.db
   volumes:
     - ./app.db:/app/app.db # persiste o banco fora do container
   restart: unless-stopped